version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./php
    container_name: php_fpm
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb:10.9
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda
      MYSQL_USER: henry
      MYSQL_PASSWORD: henry
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
